### ISSUE TITLE
consider merging with Acronyms page on the Hub

### ISSUE THREAD

**Issue by afeld** [18F/procurement-glossary#2]
https://18f.gsa.gov/hub/glossary/

**Comment by afeld** [comment]
Bump!

**Comment by jessieay** [comment]
what do you mean by "merging"?

**Comment by afeld** [comment]
I mean "have a single glossary". Totally down with converting the other terms/definitions to YAML, though not all are acronyms.

**Comment by afeld** [comment]
@vzvenyach Any objection to moving this to the `_data` directory of the Hub, and making it not procurement-specific?

**Comment by vdavez** [comment]
@afeld i went ahead and added the data from the hub in this commit https://github.com/18F/procurement-glossary/commit/335d03b39f8208ad2c329d5d458d00d581507216 as a temporary fix. I still have a vision for modular glossaries, but this is a short term hack that will lead to technical debt. :shrug:
