### ISSUE TITLE
Convert FAI glossary into YML

### ISSUE THREAD

**Issue by vdavez** [18F/procurement-glossary#5]
There's an awesome glossary of procurement terms here: https://www.fai.gov/drupal/sites/default/files/FAI_Acquisition_Glossary_021913%20Master%20Glossary.pdf
- [ ] Convert PDF into YML
- [ ] Cross-reference the abbreviations with the longform description

**Comment by vdavez** [comment]
Parking these here for later usage:
<img width="1365" alt="Screen shot of slack usage of `charlie define PWS`" src="https://cloud.githubusercontent.com/assets/4153048/12520133/c312e2d4-c110-11e5-8aab-574bdf0b6b15.png">

<img width="773" alt="Screen shot of FAI glossary including BPA" src="https://cloud.githubusercontent.com/assets/4153048/12520134/c3147b94-c110-11e5-8b49-739e572d17ee.png">

**Comment by mgwalker** [comment]
Closed due to ancientness
